interfaces.d.ts
legals.ts

Lead on #11
This pr is separated in 3 parts:

Swap from a card/set based Legal generation to a file based one

---

meta/translations/de.json

Ace Spec, Poke Body, Poke Power and Goldrenrod Game Corner were changed to the text on the german version of the relevant cards. 'Ancient Trait' doesn't have a translation on the card, so I picked the closest thing that makes sense. Some others were also mixed up/wrong and should be fixed now.

feature: Complete german meta text

---

.github/dependabot.yml

This PR fixes dependabot making PR with an incorrect name

fix: Update Dependabot to use conventional commits

---

meta/definitions/graphql.gql

Resistances and weaknesses fields werent the good type in GraphQL

fix: Fix Resistance and Weaknesses GQL being incorrect type

---

data/Base/Base Set 2/63.ts
data/Base/Fossil/50.ts
data/Base/Jungle/60.ts
data/Base/Team Rocket/19.ts
data/Base/Team Rocket/32.ts
data/Base/W Promotional.ts
data/Gym/Gym Challenge/37.ts
data/Gym/Gym Heroes/54.ts
interfaces.d.ts

W Promotional Cards do not have any other changes on them than the `W` stamp so they should ba a variant

feat: Add W Promotional variant

---

server/src/status.ts

Due to the new files used by the status page being statically imported the whole file architecture changed in the build.
This fixes it

fix: Fix server not Starting

---

data/Sun & Moon/Hidden Fates.ts

Correction fr Destinnées => Destinées

fix: Set name in french is a mistype (Hidden Fates)

---

data/XY/XY Black Star Promos/XY35.ts

"Métalosse-EEX" to "Métalosse-EX"

fix: mistype in evolveFrom name in french

---

.github/workflows/test.yml
meta/definitions/graphql.gql
server/package.json
server/src/V2/Components/Card.ts
server/src/V2/Components/Serie.ts
server/src/V2/Components/Set.ts
server/src/V2/endpoints/jsonEndpoints.ts
server/src/V2/graphql/index.ts
server/src/V2/graphql/resolver.ts
server/src/index.ts
server/src/interfaces.d.ts
server/src/status.ts
server/src/util.ts

feat: Add better sorting/filtering/pagination

---

server/src/util.ts

fix: set order not following the old way

---

.bruno/random/Random Card.bru
.bruno/random/Random Serie.bru
.bruno/random/Random Set.bru
server/src/V2/endpoints/jsonEndpoints.ts

feat: Add random card/set/serie endpoint

---

.bruno/fixes/489-crash-when-sorting-with-null-values.bru
server/src/util.ts

fix: Ordering failing when one value is null

---

data/Scarlet & Violet/Paradox Rift/266.ts

Reversal Energy is a special energy. I think the allowed values are "Special" and "Basic" in any case, but that string may come from a translation (Spanish, probably).

fix: Reversal Energy type should be "Special"

---

server/src/index.ts

Tests using k6 confirm that clustering is way better to handle more traffic on the server
http_req_duration goes from `6s` to `438ms` (when ~1000 connections are being done at the same time) allowing the server to handle from `~300req/s` to `~1500req/s`
<table class="mjsd4h0"><thead><tr class="mjsd4h2"><th align="left" class="mjsd4h1">metric</th><th align="right" class="mjsd4h1">avg</th><th align="right" class="mjsd4h1">max</th><th align="right" class="mjsd4h1">med</th><th align="right" class="mjsd4h1">min</th><th align="right" class="mjsd4h1">p90</th><th align="right" class="mjsd4h1">p95</th><th align="right" class="mjsd4h1">p99</th></tr></thead><tbody><tr class="mjsd4h3"><td align="left" class="mjsd4h4">http_req_blocked</td><td align="right" class="mjsd4h4">11µs</td><td align="right" …

feat: setup clustering

---

.bruno/fixes/562-graphql-set-request-is-not-returning-the-correct-value.bru
.bruno/graphql/card.bru
.bruno/graphql/cards.bru
.bruno/graphql/serie.bru
.bruno/graphql/series.bru
.bruno/graphql/set.bru
.bruno/graphql/sets.bru
server/src/V2/graphql/resolver.ts

fix: set id not taking into account in set search

---

data/Scarlet & Violet/Paldean Fates/010.ts
data/Scarlet & Violet/Paldean Fates/013.ts
data/Scarlet & Violet/Paldean Fates/015.ts
data/Scarlet & Violet/Paldean Fates/019.ts
data/Scarlet & Violet/Paldean Fates/024.ts
data/Scarlet & Violet/Paldean Fates/026.ts
data/Scarlet & Violet/Paldean Fates/037.ts
data/Scarlet & Violet/Paldean Fates/040.ts
data/Scarlet & Violet/Paldean Fates/043.ts
data/Scarlet & Violet/Paldean Fates/047.ts
data/Scarlet & Violet/Paldean Fates/063.ts
data/Scarlet & Violet/Paldean Fates/065.ts
data/Scarlet & Violet/Paldean Fates/067.ts
data/Scarlet & Violet/Paldean Fates/070.ts
data/Scarlet & Violet/Paldean Fates/087.ts
data/Scarlet & Violet/Paldean Fates/088.ts

This PR adds the reverse variant for holo rare cards in SV4.5: Paldean Fates
closes #601

fix: Paldean Fates holo rare cards are missing reverse variants

---

data/Scarlet & Violet/Twilight Masquerade/019.ts
data/Scarlet & Violet/Twilight Masquerade/022.ts
data/Scarlet & Violet/Twilight Masquerade/024.ts
data/Scarlet & Violet/Twilight Masquerade/033.ts
data/Scarlet & Violet/Twilight Masquerade/038.ts
data/Scarlet & Violet/Twilight Masquerade/053.ts
data/Scarlet & Violet/Twilight Masquerade/063.ts
data/Scarlet & Violet/Twilight Masquerade/065.ts
data/Scarlet & Violet/Twilight Masquerade/082.ts
data/Scarlet & Violet/Twilight Masquerade/093.ts
data/Scarlet & Violet/Twilight Masquerade/095.ts
data/Scarlet & Violet/Twilight Masquerade/096.ts
data/Scarlet & Violet/Twilight Masquerade/100.ts
data/Scarlet & Violet/Twilight Masquerade/110.ts
data/Scarlet & Violet/Twilight Masquerade/111.ts
data/Scarlet & Violet/Twilight Masquerade/123.ts

This PR adds the reverse variant for holo rare cards in SV06 Twilight Masquerade
closes https://github.com/tcgdex/cards-database/issues/599

fix: Twilight Masquerade holo rare cards are missing reverse variants

---

data/Scarlet & Violet/Temporal Forces/015.ts
data/Scarlet & Violet/Temporal Forces/021.ts
data/Scarlet & Violet/Temporal Forces/029.ts
data/Scarlet & Violet/Temporal Forces/041.ts
data/Scarlet & Violet/Temporal Forces/062.ts
data/Scarlet & Violet/Temporal Forces/078.ts
data/Scarlet & Violet/Temporal Forces/080.ts
data/Scarlet & Violet/Temporal Forces/084.ts
data/Scarlet & Violet/Temporal Forces/109.ts
data/Scarlet & Violet/Temporal Forces/117.ts
data/Scarlet & Violet/Temporal Forces/119.ts
data/Scarlet & Violet/Temporal Forces/121.ts
data/Scarlet & Violet/Temporal Forces/129.ts
data/Scarlet & Violet/Temporal Forces/138.ts

This PR adds the reverse variant for holo rare cards in SV05: Temporal Forces
closes #595

fix: Temporal Forces holo rare cards are missing reverse variants

---

data/Scarlet & Violet/151/015.ts
data/Scarlet & Violet/151/026.ts
data/Scarlet & Violet/151/034.ts
data/Scarlet & Violet/151/045.ts
data/Scarlet & Violet/151/068.ts
data/Scarlet & Violet/151/085.ts
data/Scarlet & Violet/151/094.ts
data/Scarlet & Violet/151/101.ts
data/Scarlet & Violet/151/105.ts
data/Scarlet & Violet/151/110.ts
data/Scarlet & Violet/151/113.ts
data/Scarlet & Violet/151/121.ts
data/Scarlet & Violet/151/122.ts
data/Scarlet & Violet/151/130.ts
data/Scarlet & Violet/151/132.ts
data/Scarlet & Violet/151/134.ts
data/Scarlet & Violet/151/135.ts
data/Scarlet & Violet/151/136.ts
data/Scarlet & Violet/151/139.ts
data/Scarlet & Violet/151/141.ts
data/Scarlet & Violet/151/142.ts
data/Scarlet & Violet/151/144.ts
data/Scarlet & Violet/151/145.ts
data/Scarlet & Violet/151/149.ts
data/Scarlet & Violet/151/150.ts

This PR adds the reverse variant for holo rare cards in the S&V 151 set
closes #608

fix: add missing S&V 151 reverse holo variants

---

data/Scarlet & Violet/Obsidian Flames/025.ts
data/Scarlet & Violet/Obsidian Flames/030.ts
data/Scarlet & Violet/Obsidian Flames/062.ts
data/Scarlet & Violet/Obsidian Flames/070.ts
data/Scarlet & Violet/Obsidian Flames/072.ts
data/Scarlet & Violet/Obsidian Flames/085.ts
data/Scarlet & Violet/Obsidian Flames/095.ts
data/Scarlet & Violet/Obsidian Flames/136.ts
data/Scarlet & Violet/Obsidian Flames/141.ts
data/Scarlet & Violet/Obsidian Flames/188.ts

This PR adds the reverse variant for holo rare cards in the SV03: Obsidian Flames set
closes #610

fix: add missing SV03 Obsidian Flames reverse holo variants

---

data/Scarlet & Violet/Paldea Evolved/003.ts
data/Scarlet & Violet/Paldea Evolved/011.ts
data/Scarlet & Violet/Paldea Evolved/021.ts
data/Scarlet & Violet/Paldea Evolved/033.ts
data/Scarlet & Violet/Paldea Evolved/043.ts
data/Scarlet & Violet/Paldea Evolved/056.ts
data/Scarlet & Violet/Paldea Evolved/060.ts
data/Scarlet & Violet/Paldea Evolved/071.ts
data/Scarlet & Violet/Paldea Evolved/076.ts
data/Scarlet & Violet/Paldea Evolved/079.ts
data/Scarlet & Violet/Paldea Evolved/084.ts
data/Scarlet & Violet/Paldea Evolved/089.ts
data/Scarlet & Violet/Paldea Evolved/097.ts
data/Scarlet & Violet/Paldea Evolved/098.ts
data/Scarlet & Violet/Paldea Evolved/099.ts
data/Scarlet & Violet/Paldea Evolved/105.ts
data/Scarlet & Violet/Paldea Evolved/113.ts
data/Scarlet & Violet/Paldea Evolved/123.ts
data/Scarlet & Violet/Paldea Evolved/126.ts
data/Scarlet & Violet/Paldea Evolved/134.ts
data/Scarlet & Violet/Paldea Evolved/135.ts
data/Scarlet & Violet/Paldea Evolved/136.ts
data/Scarlet & Violet/Paldea Evolved/140.ts
data/Scarlet & Violet/Paldea Evolved/151.ts
data/Scarlet & Violet/Paldea Evolved/162.ts
data/Scarlet & Violet/Paldea Evolved/172.ts
data/Scarlet & Violet/Paldea Evolved/185.ts

Fixes Paldea Evolved's variants (mainly the missing rare rev holos, but a couple other corrections too).

fix: Paldea Evolved variants are incorrect

---

.bruno/fixes/566-specific-request-crash-the-request.bru

chore : Add test for #566

---

data/Pokémon TCG Pocket/Promos-A/034.ts
data/Pokémon TCG Pocket/Promos-A/035.ts
data/Pokémon TCG Pocket/Promos-A/036.ts
data/Pokémon TCG Pocket/Promos-A/037.ts
data/Pokémon TCG Pocket/Promos-A/038.ts
data/Pokémon TCG Pocket/Promos-A/039.ts
data/Pokémon TCG Pocket/Promos-A/040.ts
data/Pokémon TCG Pocket/Promos-A/041.ts

Additional pocket promo card data, though I'm unsure how images are added

feat: Add data TCGP Promo-A 034-041

---

data/Sword & Shield/Brilliant Stars/008.ts

Changed the `normal` variant for card `008` in the `swsh9` set (Brilliant Stars) to `true` as this card also has a normal variant which can be obtained from the Build & Battle boxes.
PR made after a small discussion and confirming message on Discord: https://discord.com/channels/857231041261076491/857231041956413451/1337221782389657663
Hoping this will be a useful first contribution 🌟

fix: Add normal variant for swsh9-008

---

data/Scarlet & Violet/Obsidian Flames/148.ts
data/Scarlet & Violet/Obsidian Flames/149.ts

Added a `holo` variant for cards 148 and 149 in the sv03 (Obsidian Flames) set.
The holo variants are obtained from the Kingambit Illustration Collection from Shrouded Fable. 
Decided to also add the `normal` and `reverse` variants explicitly so card data doesn't break if the defaults ever change. Saw there are other cards that also redefine the defaults.

fix: Add holo variants for sv03-148 and sv03-149

---

data/Pokémon TCG Pocket/Mythical Island/056.ts
data/Pokémon TCG Pocket/Space-Time Smackdown/121.ts
data/Pokémon TCG Pocket/Space-Time Smackdown/122.ts
data/Pokémon TCG Pocket/Space-Time Smackdown/123.ts
data/Pokémon TCG Pocket/Space-Time Smackdown/175.ts

Remove weaknesses from Dragon cards in Pocket Mythical Island and Space-Time Smackdown sets, as they were incorrectly reporting a Colorless weakness.

fix: Remove incorrect weaknesses from Pocket A1a and A2 dragons

---

data/Scarlet & Violet/Obsidian Flames/026.ts
data/Scarlet & Violet/Obsidian Flames/027.ts

Added a holo variant for cards 026 and 027 in the sv03 (Obsidian Flames) set.
The holo variants are obtained from the Charizard EX Premium Collection 
Decided to also add the normal and reverse variants explicitly so card data doesn't break if the defaults ever change. Saw there are other cards that also redefine the defaults.

fix: Add holo variants for sv03-023 and sv03-027

---

data/Pokémon TCG Pocket/Genetic Apex/023.ts

This PR updates incorrect Exeggutor ex attack name as stated in this issue: https://github.com/tcgdex/cards-database/issues/681

Fix Exeggutor ex attack name

---

data/Scarlet & Violet/Scarlet & Violet/134.ts

Added a reverse holo variant for card 134 (Kingambit) in the sv01 (Scarlet & Violet base) set.
Reverse holo variant can be obtained through checklane bundle.

fix: Add reverse holo variant for sv01-134

---

data/Scarlet & Violet/Obsidian Flames/062.ts

Added normal variant for card 062 (Palafin) in the sv03 (Obsidian Flame) set.
Normal variant can be obtained through Obsidian Flame Build & Battle box.
Added known variants in a verbose matter to prevent issues when default change

fix: Add normal variant for sv03-062

---

data/Scarlet & Violet/Scarlet & Violet/190.ts

Added normal variant for card 190 (Professor's Research) in the sv01 (Scarlet & Violet base) set.
Normal variant can be obtained through Obsidian Flame Build & Battle box.

fix: Add normal variant for sv01-190

---

data/Trainer kits/DP trainer Kit (Lucario)/1.ts

Hi, i added a card which is included in the set: trainer Kit (Lucario) with the set_id: tk-dp-l
there are still more cards missing to the trainer Kits and I experienced many more missing cards. I would gladly help out to add those, since I'm using the API for my own purpose.

feat: Add 1 Missing card in tk-dp-l

---

data/Pokémon TCG Pocket/Promos-A/042.ts
data/Pokémon TCG Pocket/Promos-A/043.ts
data/Pokémon TCG Pocket/Promos-A/044.ts
data/Pokémon TCG Pocket/Promos-A/045.ts
data/Pokémon TCG Pocket/Promos-A/046.ts
data/Pokémon TCG Pocket/Promos-A/047.ts
data/Pokémon TCG Pocket/Promos-A/048.ts
data/Pokémon TCG Pocket/Promos-A/049.ts
data/Pokémon TCG Pocket/Promos-A/050.ts
data/Pokémon TCG Pocket/Promos-A/051.ts
data/Pokémon TCG Pocket/Promos-A/052.ts
data/Pokémon TCG Pocket/Promos-A/053.ts
data/Pokémon TCG Pocket/Promos-A/054.ts
data/Pokémon TCG Pocket/Promos-A/055.ts
data/Pokémon TCG Pocket/Promos-A/056.ts
data/Pokémon TCG Pocket/Promos-A/057.ts
data/Pokémon TCG Pocket/Promos-A/058.ts
data/Pokémon TCG Pocket/Promos-A/059.ts

feat: Add data TCGP Promo-A 042-059 (March 2025)

---

data/Pokémon TCG Pocket/Shining Revelry.ts
data/Pokémon TCG Pocket/Shining Revelry/004.ts
data/Pokémon TCG Pocket/Shining Revelry/005.ts
data/Pokémon TCG Pocket/Shining Revelry/007.ts
data/Pokémon TCG Pocket/Shining Revelry/010.ts
data/Pokémon TCG Pocket/Shining Revelry/024.ts
data/Pokémon TCG Pocket/Shining Revelry/025.ts
data/Pokémon TCG Pocket/Shining Revelry/032.ts
data/Pokémon TCG Pocket/Shining Revelry/038.ts
data/Pokémon TCG Pocket/Shining Revelry/039.ts
data/Pokémon TCG Pocket/Shining Revelry/044.ts
data/Pokémon TCG Pocket/Shining Revelry/048.ts
data/Pokémon TCG Pocket/Shining Revelry/053.ts
data/Pokémon TCG Pocket/Shining Revelry/054.ts
data/Pokémon TCG Pocket/Shining Revelry/057.ts
data/Pokémon TCG Pocket/Shining Revelry/073.ts
data/Pokémon TCG Pocket/Shining Revelry/077.ts
data/Pokémon TCG Pocket/Shining Revelry/080.ts
data/Pokémon TCG Pocket/Shining Revelry/086.ts
data/Pokémon TCG Pocket/Shining Revelry/094.ts
data/Pokémon TCG Pocket/Shining Revelry/103.ts
data/Pokémon TCG Pocket/Shining Revelry/108.ts

Make amendments to correct card data for A2b:
* Attacks with additional or multiplied damage were missing + and x symbols respectively
* Energy symbols were stripped from card text. 
- I've added these back in square brackets (eg `[Fire]`, `[Grass]` etc), as we don't currently have a consistent way to represent them`*`. 
`*` For Pocket, we currently use span tags for most sets (eg `<span class=\"energy-text energy-text--type-fire\"></span>` and symbol font characters for Genetic Apex (eg `R` for Fire, `G` for Grass etc), likely due to the initial source of data. It would be helpful for API consumers if we could standardise to one format, I've raised issue #697 to discuss this further.

Fix: A2b Shining Revelry attack amendments

---

data/XY/Kalos Starter Set.ts

fix: invalid card count in Kalos starter set

---

data/Scarlet & Violet/Destined Rivals/144.ts

Card is not available in Holo, only normal/reverse

fix: Update SV/DRI/144 variants
