tcgdex/cards-database

data/Diamond & Pearl.ts, data/Diamond & Pearl/DP Black Star Promos.ts, data/Diamond & Pearl/Diamond & Pearl.ts, data/Diamond & Pearl/Great Encounters.ts, data/Diamond & Pearl/Legends Awakened.ts, data/Diamond & Pearl/Majestic Dawn.ts, data/Diamond & Pearl/Mysterious Treasures.ts, data/Diamond & Pearl/Secret Wonders.ts, data/Diamond & Pearl/Stormfront.ts
=> Added DP sets  translations

data/XY.ts, data/XY/Ancient Origins.ts, data/XY/BREAKpoint.ts, data/XY/BREAKthrough.ts, data/XY/Double Crisis.ts, data/XY/Evolutions.ts, data/XY/Fates Collide.ts, data/XY/Flashfire.ts, data/XY/Furious Fists.ts, data/XY/Generations.ts, data/XY/Kalos Starter Set.ts, data/XY/Phantom Forces.ts, data/XY/Primal Clash.ts, data/XY/Roaring Skies.ts, data/XY/Steam Siege.ts, data/XY/XY Black Star Promos.ts, data/XY/XY.ts, data/XY/Yello A Alternate.ts
=> Added XY sets Translations

data/Black & White.ts, data/Black & White/BW Black Star Promos.ts, data/Black & White/Black & White.ts, data/Black & White/Boundaries Crossed.ts, data/Black & White/Dark Explorers.ts, data/Black & White/Dragons Exalted.ts, data/Black & White/Emerging Powers.ts, data/Black & White/Next Destinies.ts, data/Black & White/Noble Victories.ts, data/Black & White/Plasma Blast.ts, data/Black & White/Plasma Freeze.ts, data/Black & White/Plasma Storm.ts
=> Added Black & White sets Translations

data/Call of Legends.ts, data/Call of Legends/Call of Legends.ts
=> Added Call of Legends set Translation

data/HeartGold & SoulSilver.ts, data/HeartGold & SoulSilver/HGSS Black Star Promos.ts, data/HeartGold & SoulSilver/HeartGold SoulSilver.ts, data/HeartGold & SoulSilver/Triumphant.ts, data/HeartGold & SoulSilver/Undaunted.ts, data/HeartGold & SoulSilver/Unleashed.ts
=> Added HeartGold & SoulSilver sets translations

data/Platinum.ts, data/Platinum/Arceus.ts, data/Platinum/Platinum.ts, data/Platinum/Rising Rivals.ts, data/Platinum/Supreme Victors.ts
=> Added Platinum sets Translations

server/compiler/utils/setUtil.ts, server/compiler/utils/util.ts, server/package.json, tsconfig.json
Signed-off-by: Avior <github@avior.me>
=> fix: Fixed DB path

server/compiler/endpoints/series.ts, server/compiler/endpoints/sets.ts
Signed-off-by: Avior <github@avior.me>
=> Fix: duplication bug

server/src/V2/endpoints/jsonEndpoints.ts
Signed-off-by: Avior <github@avior.me>
=> fix: /cards endpoint giving the full card datas

.github/workflows/conventionnal-commit.yml
=> fix: Change to use angular conventional changelog

server/src/V2/Components/Set.ts
=> fix: Fix /sets/:id endpoint to check in lowercase

data/Base/Base Set/1.ts
Randomly stumbled across this one
=> fix: Fix typo in base1-1

data/Sword & Shield/Fusion Strike.ts
=> fix: Fusion Strike id

server/src/V2/Components/Serie.ts
Signed-off-by: Avior <github@avior.me>
=> fix: Make /series/:serie case insensitive

server/src/V2/Components/Card.ts, server/src/V2/Components/Set.ts
Fixed two small bugs not correcly parsing some requests
=> fix: JSON endpoints not working as intended

server/src/V2/Components/Card.ts, server/src/V2/Components/Set.ts
=> fix: incorrect set being reconized

.vscode/settings.json, server/src/V2/Components/Card.ts, server/src/V2/Components/Serie.ts, server/src/V2/Components/Set.ts, server/src/V2/endpoints/jsonEndpoints.ts, server/src/util.ts
Fix the missing bug by changing to a better equality checker
=> fix: Misc Endpoints not working  as intended

data/EX/Poké Card Creator Pack.ts, data/EX/Poké Card Creator Pack/1.ts, data/EX/Poké Card Creator Pack/2.ts, data/EX/Poké Card Creator Pack/3.ts, data/EX/Poké Card Creator Pack/4.ts, data/EX/Poké Card Creator Pack/5.ts
=> feat: Add Poké Card Creator Pack cards

data/Base/Jungle.ts
Edit french "Jungla" to "Jungle"
=> fix: Fix Jungle French name

server/src/V2/Components/Card.ts, server/src/V2/Components/Serie.ts, server/src/V2/Components/Set.ts
Some endpoints weren't giving the correct card
=> fix: Fix Endpoints not giving the correct card with a speicific id

package-lock.json, server/package-lock.json, server/src/V2/endpoints/jsonEndpoints.ts, server/src/util.ts
StringEndpoint weren't corresponding to the Docs, breaking the php-sdk that use it for tests
=> fix: StringEndpoint not corresponding to the docs

server/src/V2/graphql/index.ts
=> refactor: Add more logging forGraphQL errors

server/src/V2/Components/Card.ts, server/src/util.ts
=> perf: Remove Uneeded logging

data/Sword & Shield/Battle Styles.ts, data/Sword & Shield/Battle Styles/35.ts
=> fix: Battle Styles has the correct card count

data/Sword & Shield/SWSH Black Star Promos.ts
=> fix: Add Sword & Shield Portuguese promos set name

server/src/status.ts
=> fix: Fix Total progress without the correct pre language progress

README.md, meta/definitions/graphql.gql, server/README.md, server/src/status.ts
Added github.svg endpoint for the README table
=> feat: Add Github Table as SVG

server/src/V2/graphql/resolver.ts
=> fix: Handle variable lang directive

package-lock.json, server/package-lock.json, server/package.json
=> build: Upgrade Deps

.github/workflows/build.yml
=> feat: Add built image to dockerhub

meta/definitions/graphql.gql
=> chore: Document the GraphQL definition

meta/legals.ts
=> chore: Update legal cards for the 2023 season

server/src/index.ts
=> fix: invalid `OPTIONS` request handling

.bruno/GraphQL API.bru, .bruno/Validate that we can run OPTIONS.bru, .bruno/bruno.json, .bruno/cards/get Card list.bru, .bruno/cards/get one card.bru, .bruno/environments/Developpement.bru, .bruno/environments/Production.bru, .bruno/fixes/invalid sorting.bru, .bruno/sets/get a set.bru, .bruno/sets/get list of sets.bru, .bruno/sets/get one card from a set.bru
=> feat: Add bruno to tests the APIs

.bruno/fixes/474-queries-crashing-the-server.bru, server/src/util.ts
=> fix: Undefined values crashing the request

.bruno/fixes/467-options-not-working-correctly.bru, .bruno/fixes/471-invalid-set-sorting.bru, .bruno/fixes/475-ability-query-subfields.bru, server/src/util.ts
=> feat: Add ability for users to requests using the subfields values

meta/translations/pt.json
Thanks to @glaucoperucchi on Discord for the updated file
=> chore: Add metadata for Portuguese

.github/workflows/build.yml
=> fix: Updated field not working as intended

.github/PULL_REQUEST_TEMPLATE.md
=> chore: unused text

.github/workflows/build.yml
=> chore: disable push to Docker for forks

.github/workflows/build.yml
=> fix: dependabot still has permission

data/Sword & Shield/Brilliant Stars/008.ts, data/Sword & Shield/Celebrations/107A.ts, data/Sword & Shield/Celebrations/109A.ts, data/Sword & Shield/Celebrations/113A.ts, data/Sword & Shield/Celebrations/114A.ts, data/Sword & Shield/Celebrations/145A.ts, data/Sword & Shield/Celebrations/15A.ts, data/Sword & Shield/Celebrations/15A1.ts, data/Sword & Shield/Celebrations/15A2.ts, data/Sword & Shield/Celebrations/15A3.ts, data/Sword & Shield/Celebrations/15A4.ts, data/Sword & Shield/Celebrations/17A.ts, data/Sword & Shield/Celebrations/20A.ts, data/Sword & Shield/Celebrations/24A.ts, data/Sword & Shield/Celebrations/25.ts, data/Sword & Shield/Celebrations/2A.ts, data/Sword & Shield/Celebrations/4A.ts, data/Sword & Shield/Celebrations/54A.ts, data/Sword & Shield/Celebrations/60A.ts, data/Sword & Shield/Celebrations/66A.ts, data/Sword & Shield/Celebrations/73A.ts, data/Sword & Shield/Celebrations/76A.ts, data/Sword & Shield/Celebrations/86A.ts, data/Sword & Shield/Celebrations/88A.ts, data/Sword & Shield/Celebrations/8A.ts, data/Sword & Shield/Celebrations/93A.ts, data/Sword & Shield/Celebrations/97A.ts, data/Sword & Shield/Celebrations/9A.ts
=> editor: misc fixes for variants

data/Sword & Shield/Vivid Voltage.ts, meta/legals.ts
=> feat: update format rotation to 2024

.bruno/cards/advanced-query.bru, .bruno/cards/multiple.bru, server/src/libs/QueryEngine/parsers.ts
=> fix: Add missing multi value filtering

.bruno/fixes/567-invalid-data-returned-when-filtering-using-set.bru, server/src/V2/endpoints/jsonEndpoints.ts
=> fix: no data was returned when filtering with `set`

data/XY/Ancient Origins.ts, data/XY/BREAKthrough.ts, data/XY/Flashfire.ts, data/XY/Furious Fists.ts, data/XY/Phantom Forces.ts, data/XY/Primal Clash.ts, data/XY/Roaring Skies.ts, data/XY/XY.ts
=> chore: Add russian set names

data/Diamond & Pearl/Diamond & Pearl.ts, data/Diamond & Pearl/Mysterious Treasures.ts
=> chore: Add polish sets names

data/Base/Base Set.ts, data/Base/Fossil.ts, data/Base/Jungle.ts
=> chore: Add Dutch sets names

data/Pokémon TCG Pocket/Genetic Apex/005.ts, data/Pokémon TCG Pocket/Genetic Apex/006.ts, data/Pokémon TCG Pocket/Genetic Apex/007.ts, data/Pokémon TCG Pocket/Genetic Apex/008.ts, data/Pokémon TCG Pocket/Genetic Apex/009.ts, data/Pokémon TCG Pocket/Genetic Apex/010.ts, data/Pokémon TCG Pocket/Genetic Apex/011.ts, data/Pokémon TCG Pocket/Genetic Apex/012.ts, data/Pokémon TCG Pocket/Genetic Apex/013.ts, data/Pokémon TCG Pocket/Genetic Apex/014.ts, data/Pokémon TCG Pocket/Genetic Apex/015.ts, data/Pokémon TCG Pocket/Genetic Apex/017.ts, data/Pokémon TCG Pocket/Genetic Apex/018.ts, data/Pokémon TCG Pocket/Genetic Apex/019.ts, data/Pokémon TCG Pocket/Genetic Apex/020.ts
=> editor: Edited some rarities

data/Pokémon TCG Pocket/Promos-A.ts, data/Pokémon TCG Pocket/Promos-A/001.ts, data/Pokémon TCG Pocket/Promos-A/002.ts, data/Pokémon TCG Pocket/Promos-A/003.ts, data/Pokémon TCG Pocket/Promos-A/004.ts, data/Pokémon TCG Pocket/Promos-A/005.ts, data/Pokémon TCG Pocket/Promos-A/006.ts, data/Pokémon TCG Pocket/Promos-A/007.ts, data/Pokémon TCG Pocket/Promos-A/009.ts, data/Pokémon TCG Pocket/Promos-A/010.ts, data/Pokémon TCG Pocket/Promos-A/011.ts, data/Pokémon TCG Pocket/Promos-A/012.ts, data/Pokémon TCG Pocket/Promos-A/013.ts, data/Pokémon TCG Pocket/Promos-A/014.ts, data/Pokémon TCG Pocket/Promos-A/015.ts, data/Pokémon TCG Pocket/Promos-A/016.ts, data/Pokémon TCG Pocket/Promos-A/017.ts, data/Pokémon TCG Pocket/Promos-A/018.ts, data/Pokémon TCG Pocket/Promos-A/019.ts, data/Pokémon TCG Pocket/Promos-A/020.ts, data/Pokémon TCG Pocket/Promos-A/021.ts, data/Pokémon TCG Pocket/Promos-A/022.ts, data/Pokémon TCG Pocket/Promos-A/023.ts, data/Pokémon TCG Pocket/Promos-A/024.ts
=> feat: Add TCG Pocket promos A

server/src/V2/endpoints/jsonEndpoints.ts
=> fix: random card not respecting format

meta/definitions/api.d.ts, server/compiler/utils/serieUtil.ts
=> feat: Add firstSet and lastSet properties to Serie interface

server/src/index.ts
=> feat: Allow to customize number of workers

data/Pokémon TCG Pocket/Promos-A/001.ts, data/Pokémon TCG Pocket/Promos-A/002.ts, data/Pokémon TCG Pocket/Promos-A/003.ts, data/Pokémon TCG Pocket/Promos-A/004.ts, data/Pokémon TCG Pocket/Promos-A/006.ts, data/Pokémon TCG Pocket/Promos-A/007.ts, data/Pokémon TCG Pocket/Promos-A/008.ts, data/Pokémon TCG Pocket/Promos-A/010.ts, data/Pokémon TCG Pocket/Promos-A/011.ts, data/Pokémon TCG Pocket/Promos-A/012.ts, data/Pokémon TCG Pocket/Promos-A/013.ts, data/Pokémon TCG Pocket/Promos-A/015.ts, data/Pokémon TCG Pocket/Promos-A/016.ts, data/Pokémon TCG Pocket/Promos-A/017.ts, data/Pokémon TCG Pocket/Promos-A/018.ts, data/Pokémon TCG Pocket/Promos-A/019.ts, data/Pokémon TCG Pocket/Promos-A/020.ts, data/Pokémon TCG Pocket/Promos-A/021.ts, data/Pokémon TCG Pocket/Promos-A/024.ts, data/Pokémon TCG Pocket/Promos-A/025.ts, data/Pokémon TCG Pocket/Promos-A/026.ts, data/Pokémon TCG Pocket/Promos-A/027.ts, data/Pokémon TCG Pocket/Promos-A/028.ts, data/Pokémon TCG Pocket/Promos-A/029.ts, data/Pokémon TCG Pocket/Promos-A/030.ts, data/Pokémon TCG Pocket/Promos-A/031.ts, data/Pokémon TCG Pocket/Promos-A/032.ts, data/Pokémon TCG Pocket/Promos-A/033.ts
=> feat: Add the new Pokémon TCG Pocket promos

server/src/libs/QueryEngine/parsers.ts
=> [#566] fix: specific request crash

docker-compose.yml
=> chore: add example docker-compose file

meta/definitions/api.d.ts, server/compiler/utils/serieUtil.ts
=> feat: add release date to series

data/Scarlet & Violet/Obsidian Flames/072.ts
It would be my first contribution, I hope it's supposed to be like that but as I reported the issue #643 I tried to commit the patch that go with and add the 3 variations I have.
I can prove they exists at least with this ![IMG20250124094842](https://github.com/user-attachments/assets/c6e93b0f-4cd4-4558-b9aa-929022071614)
=> Added missing variants

data/Pokémon TCG Pocket/Mythical Island/063.ts
=> fix: missing 063 in A1a

data/Scarlet & Violet/SVP Black Star Promos/085.ts, data/Scarlet & Violet/SVP Black Star Promos/102.ts, data/Scarlet & Violet/SVP Black Star Promos/167.ts, data/Scarlet & Violet/SVP Black Star Promos/168.ts, data/Scarlet & Violet/SVP Black Star Promos/169.ts, data/Scarlet & Violet/SVP Black Star Promos/170.ts, data/Scarlet & Violet/SVP Black Star Promos/171.ts, data/Scarlet & Violet/SVP Black Star Promos/172.ts, data/Scarlet & Violet/SVP Black Star Promos/173.ts, data/Scarlet & Violet/SVP Black Star Promos/190.ts, data/Scarlet & Violet/Stellar Crown.ts
- Add info promo cards SVP (en & pt);
- Add abbreviations on Stellar Crown;
=> Feat: Add cards svp promos and add abbreviations official stellar crown

server/compiler/utils/serieUtil.ts
=> fix: Find a better image for the serie logo

server/src/index.ts
=> fix: random exit from worker making server not react

meta/legals.ts
=> 2025 Rotation

data/Scarlet & Violet/Prismatic Evolutions.ts
=> FIX: Prismatic Evolutions set name (Spanish)

data/POP/POP Series 3/1.ts
Updated 
"evolveFrom": "Unown"
to
"evolveFrom": "Wartortle"
=> Fix evolveFrom for Card 1 of POP Series 3 set

data/Pokémon TCG Pocket/Promos-A/005.ts, data/Pokémon TCG Pocket/Promos-A/010.ts, data/Pokémon TCG Pocket/Promos-A/025.ts, data/Pokémon TCG Pocket/Promos-A/028.ts, data/Pokémon TCG Pocket/Promos-A/029.ts, data/Pokémon TCG Pocket/Promos-A/032.ts, data/Pokémon TCG Pocket/Promos-A/036.ts, data/Pokémon TCG Pocket/Promos-A/037.ts, data/Pokémon TCG Pocket/Promos-A/038.ts, data/Pokémon TCG Pocket/Promos-A/047.ts, data/Pokémon TCG Pocket/Promos-A/050.ts, data/Pokémon TCG Pocket/Promos-A/052.ts, data/Pokémon TCG Pocket/Promos-A/054.ts, data/Pokémon TCG Pocket/Promos-A/055.ts, data/Pokémon TCG Pocket/Promos-A/060.ts, data/Pokémon TCG Pocket/Promos-A/061.ts, data/Pokémon TCG Pocket/Promos-A/062.ts, data/Pokémon TCG Pocket/Promos-A/063.ts, data/Pokémon TCG Pocket/Promos-A/064.ts, data/Pokémon TCG Pocket/Promos-A/065.ts, data/Pokémon TCG Pocket/Promos-A/066.ts, data/Pokémon TCG Pocket/Promos-A/067.ts, data/Pokémon TCG Pocket/Promos-A/068.ts, data/Pokémon TCG Pocket/Promos-A/069.ts, data/Pokémon TCG Pocket/Promos-A/070.ts, data/Pokémon TCG Pocket/Promos-A/071.ts, data/Pokémon TCG Pocket/Promos-A/072.ts, data/Pokémon TCG Pocket/Promos-A/073.ts
=> feat: update TCG Promos and fix some issues

data/Scarlet & Violet/Journey Together/056.ts, data/Scarlet & Violet/Journey Together/173.ts, data/Scarlet & Violet/Journey Together/184.ts
=> fix: lillie's clefairy EX having an additionnal attack

.github/workflows/build.yml
=> fix: allow forks to run the build

data/Scarlet & Violet/Prismatic Evolutions/002.ts, data/Scarlet & Violet/Prismatic Evolutions/003.ts
=> editor: real changes inside a test

data/Scarlet & Violet/Prismatic Evolutions/001.ts
=> editor: 7186

.github/scripts/load-cards.ts
=> refactor: get the full list of cards

.github/workflows/comment-pr.yml
=> chore: run comment-pr  when it is edited

.github/workflows/build.yml, .github/workflows/test.yml
=> chore: optimize github actions runtime

meta/definitions/graphql.gql
=> fix: server runtime error

data/Base/Base Set/2.ts
=> editor: changed retreat cost

data/Pokémon TCG Pocket/Extradimensional Crisis.ts
=> fix: invalid cardcount

data/Scarlet & Violet/Black Bolt.ts, data/Scarlet & Violet/White Flare.ts
=> fix: invalid name of sv11

.github/workflows/test.yml
=> chore: allow PRs to run tests

server/src/index.ts
=> chore: add monitoring endpoint
